# SQLite Database Usage Instructions

This document explains how to use SQLite with ${projectName}.

## Configuration

SQLite is a file-based database. The database file is located at:
```
data/${projectName}.db
```

No additional configuration needed - SQLite is included with Python!

## Prerequisites

**None!** SQLite comes bundled with Python. No installation required.

## Usage

### Basic Connection

```python
from config.db_connection import get_db_connection, get_db_session

# Get engine
engine = get_db_connection()

# Get session
session = get_db_session()
```

### Using Context Manager

```python
from config.db_connection import DatabaseSession
from sqlalchemy import text

# Execute query with automatic session management
with DatabaseSession() as session:
    result = session.execute(text("SELECT sqlite_version()"))
    version = result.fetchone()
    print(f"SQLite version: {version[0]}")
```

### Creating Models

```python
from config.db_connection import Base
from sqlalchemy import Column, Integer, String, DateTime
from datetime import datetime

class User(Base):
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(50), unique=True, nullable=False)
    email = Column(String(100), unique=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

# Create tables
from config.db_connection import engine
Base.metadata.create_all(bind=engine)
```

### CRUD Operations

```python
from config.db_connection import DatabaseSession

# Create
with DatabaseSession() as session:
    new_user = User(username="john_doe", email="john@example.com")
    session.add(new_user)
    session.commit()
    session.refresh(new_user)
    print(f"Created user with ID: {new_user.id}")

# Read
with DatabaseSession() as session:
    users = session.query(User).all()
    for user in users:
        print(f"User: {user.username} ({user.email})")

# Update
with DatabaseSession() as session:
    user = session.query(User).filter_by(username="john_doe").first()
    if user:
        user.email = "newemail@example.com"
        session.commit()

# Delete
with DatabaseSession() as session:
    user = session.query(User).filter_by(username="john_doe").first()
    if user:
        session.delete(user)
        session.commit()
```

## Database File Location

The SQLite database file is stored at: `data/${projectName}.db`

This file is automatically created when you first run your application.

## Backup & Restore

### Backup
```bash
# Simply copy the database file
cp data/${projectName}.db data/${projectName}.db.backup
```

### Restore
```bash
# Copy backup back
cp data/${projectName}.db.backup data/${projectName}.db
```

## SQLite Browser

To visually inspect your database, use DB Browser for SQLite:
- Download: https://sqlitebrowser.org/
- Open: `data/${projectName}.db`

## Advantages of SQLite

- **Zero configuration** - No server setup required
- **Portable** - Single file database
- **Fast** - Great for development and small applications
- **Built-in** - No external dependencies

## Limitations

- **Not suitable for high concurrency** - Single writer at a time
- **Not ideal for large datasets** - Better options exist for big data
- **No network access** - File-based only

## When to Use SQLite

✅ **Good for:**
- Development and testing
- Small to medium applications
- Desktop applications
- Prototypes
- Embedded systems

❌ **Not recommended for:**
- High-traffic web applications
- Multi-user concurrent writes
- Large-scale production systems

## Migrations

For database migrations, consider using Alembic:

```bash
# Install Alembic
pip install alembic

# Initialize Alembic
alembic init alembic

# Create migration
alembic revision --autogenerate -m "Create users table"

# Apply migration
alembic upgrade head
```

## Best Practices

1. **Use context managers** for automatic session cleanup
2. **Create indexes** for frequently queried columns
3. **Regular backups** - Just copy the .db file
4. **Use WAL mode** for better concurrency (enabled by default)
5. **Vacuum regularly** to optimize file size

## Resources

- SQLite Documentation: https://www.sqlite.org/docs.html
- SQLAlchemy Documentation: https://docs.sqlalchemy.org/
- DB Browser for SQLite: https://sqlitebrowser.org/

---

Generated by Genesis - ${currentDate}
