# JWT Authentication Guide

This document explains how to use JWT authentication in ${projectName}.

## What is JWT?

JWT (JSON Web Token) is a secure way to transmit information between parties as a JSON object. It's commonly used for API authentication.

## Configuration

JWT settings are in `.env`:

```env
JWT_SECRET_KEY=your-jwt-secret-here-change-in-production
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
```

**⚠️ IMPORTANT:** Change the `JWT_SECRET_KEY` in production!

## Basic Usage

### Creating Tokens

```python
from config.jwt_handler import create_access_token

# Create token for a user
token = create_access_token(data={"sub": "user@example.com"})
print(f"Token: {token}")

# Create token with custom expiration (1 hour)
from datetime import timedelta
token = create_access_token(
    data={"sub": "user@example.com"},
    expires_delta=timedelta(hours=1)
)
```

### Verifying Tokens

```python
from config.jwt_handler import verify_token, get_user_from_token

# Verify token and get payload
payload = verify_token(token)
if payload:
    print(f"Valid token for: {payload['sub']}")
else:
    print("Invalid or expired token")

# Get user directly
user = get_user_from_token(token)
```

<#if has_flask??>
## Flask Integration

### Protecting Routes

```python
from flask import Flask, jsonify
from config.jwt_handler import token_required, create_access_token

app = Flask(__name__)

@app.route('/login', methods=['POST'])
def login():
    # Validate user credentials here
    username = "user@example.com"

    # Create token
    token = create_access_token(data={"sub": username})

    return jsonify({
        'access_token': token,
        'token_type': 'bearer'
    })

@app.route('/protected')
@token_required
def protected_route(current_user):
    return jsonify({
        'message': f'Hello {current_user}',
        'data': 'This is protected data'
    })
```

### Client Request Example

```python
import requests

# Login
response = requests.post('http://localhost:5000/login')
token = response.json()['access_token']

# Access protected route
headers = {'Authorization': f'Bearer {token}'}
response = requests.get('http://localhost:5000/protected', headers=headers)
print(response.json())
```

</#if>
<#if has_fastapi??>
## FastAPI Integration

### Protecting Routes

```python
from fastapi import FastAPI, Depends
from config.jwt_handler import create_access_token, get_current_user

app = FastAPI()

@app.post("/login")
async def login():
    # Validate user credentials here
    username = "user@example.com"

    # Create token
    token = create_access_token(data={"sub": username})

    return {
        'access_token': token,
        'token_type': 'bearer'
    }

@app.get("/protected")
async def protected_route(current_user: str = Depends(get_current_user)):
    return {
        'message': f'Hello {current_user}',
        'data': 'This is protected data'
    }
```

### Client Request Example

```python
import requests

# Login
response = requests.post('http://localhost:8000/login')
token = response.json()['access_token']

# Access protected route
headers = {'Authorization': f'Bearer {token}'}
response = requests.get('http://localhost:8000/protected', headers=headers)
print(response.json())
```

</#if>
## Token Claims

You can add custom claims to your tokens:

```python
token = create_access_token(data={
    "sub": "user@example.com",
    "role": "admin",
    "permissions": ["read", "write"]
})
```

## Security Best Practices

1. **Use strong secret keys** - Generate with: `python -c "import secrets; print(secrets.token_urlsafe(32))"`
2. **Use HTTPS in production** - Never send tokens over HTTP
3. **Short expiration times** - 15-30 minutes for access tokens
4. **Implement refresh tokens** - For longer sessions
5. **Store tokens securely** - Use httpOnly cookies or secure storage
6. **Validate all claims** - Don't trust token data without verification

## Common Issues

### "Token is invalid"
- Token may be expired (check `exp` claim)
- Secret key mismatch
- Token format incorrect (should be "Bearer <token>")

### "Token format invalid"
- Ensure Authorization header: `Authorization: Bearer <token>`
- No "Bearer" prefix or wrong format

## Resources

- JWT.io: https://jwt.io/
- PyJWT Documentation: https://pyjwt.readthedocs.io/
- RFC 7519: https://tools.ietf.org/html/rfc7519

---

Generated by Genesis - ${currentDate}
