# MySQL Database Usage Instructions

This document explains how to use MySQL with ${projectName}.

## Configuration

Database settings are configured in `.env` file:

```env
DATABASE_URL=mysql+pymysql://root:password@localhost:3306/${projectName}
DB_HOST=localhost
DB_PORT=3306
DB_NAME=${projectName}
DB_USER=root
DB_PASSWORD=your_password_here
```

## Prerequisites

1. **Install MySQL:**
   - Ubuntu/Debian: `sudo apt-get install mysql-server`
   - macOS: `brew install mysql`
   - Windows: Download from https://dev.mysql.com/downloads/mysql/

2. **Start MySQL service:**
   ```bash
   # Linux
   sudo service mysql start

   # macOS
   brew services start mysql

   # Windows
   # MySQL service starts automatically
   ```

3. **Create database:**
   ```bash
   # Login to MySQL
   mysql -u root -p

   # Create database
   CREATE DATABASE ${projectName};

   # Create user (optional)
   CREATE USER '${projectName}_user'@'localhost' IDENTIFIED BY 'your_password';
   GRANT ALL PRIVILEGES ON ${projectName}.* TO '${projectName}_user'@'localhost';
   FLUSH PRIVILEGES;

   # Exit
   exit;
   ```

## Usage

### Basic Connection

```python
from config.db_connection import get_db_connection, get_db_session

# Get engine
engine = get_db_connection()

# Get session
session = get_db_session()
```

### Using Context Manager

```python
from config.db_connection import DatabaseSession
from sqlalchemy import text

# Execute query with automatic session management
with DatabaseSession() as session:
    result = session.execute(text("SELECT VERSION()"))
    version = result.fetchone()
    print(f"MySQL version: {version[0]}")
```

### Creating Models

```python
from config.db_connection import Base
from sqlalchemy import Column, Integer, String, DateTime
from datetime import datetime

class User(Base):
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(50), unique=True, nullable=False)
    email = Column(String(100), unique=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

# Create tables
from config.db_connection import engine
Base.metadata.create_all(bind=engine)
```

### CRUD Operations

```python
from config.db_connection import DatabaseSession

# Create
with DatabaseSession() as session:
    new_user = User(username="john_doe", email="john@example.com")
    session.add(new_user)
    session.commit()
    session.refresh(new_user)
    print(f"Created user with ID: {new_user.id}")

# Read
with DatabaseSession() as session:
    users = session.query(User).all()
    for user in users:
        print(f"User: {user.username} ({user.email})")

# Update
with DatabaseSession() as session:
    user = session.query(User).filter_by(username="john_doe").first()
    if user:
        user.email = "newemail@example.com"
        session.commit()

# Delete
with DatabaseSession() as session:
    user = session.query(User).filter_by(username="john_doe").first()
    if user:
        session.delete(user)
        session.commit()
```

## Troubleshooting

### Connection refused
- Ensure MySQL is running: `sudo service mysql status`
- Check if MySQL is listening: `sudo netstat -plnt | grep 3306`

### Authentication failed
- Check username and password in `.env`
- Verify user permissions in MySQL
- Try: `mysql -u root -p` to test credentials

### Database does not exist
- Create the database: `CREATE DATABASE ${projectName};`

## Best Practices

1. **Always use context managers** for automatic session cleanup
2. **Never commit credentials** to version control
3. **Use connection pooling** for better performance
4. **Use parameterized queries** to prevent SQL injection
5. **Close sessions properly** to avoid connection leaks

## Resources

- MySQL Documentation: https://dev.mysql.com/doc/
- SQLAlchemy Documentation: https://docs.sqlalchemy.org/
- PyMySQL Documentation: https://pymysql.readthedocs.io/

---

Generated by Genesis - ${currentDate}
