"""
Streamlit Dashboard Application for ${projectName}
Create interactive data apps and dashboards with Python
"""

import streamlit as st
import logging

<#if hasDatabase>
<#if has_mongodb??>
from config.db_connection import get_collection
<#elseif has_redis??>
from config.db_connection import get_redis_client
<#else>
from config.db_connection import get_db_session
</#if>
</#if>

logger = logging.getLogger(__name__)


# Page configuration
st.set_page_config(
    page_title="${projectName}",
    page_icon="🚀",
    layout="wide",
    initial_sidebar_state="expanded"
)


def main():
    """Main Streamlit application"""

    # Title
    st.title("🚀 ${projectName}")
    st.markdown("---")

    # Sidebar
    with st.sidebar:
        st.header("Settings")
        st.markdown("${description}")

        # Example sidebar inputs
        option = st.selectbox(
            "Select an option:",
            ["Option 1", "Option 2", "Option 3"]
        )

    # Main content
    st.header("Welcome to ${projectName}")

    # Create tabs
    tab1, tab2<#if hasDatabase>, tab3</#if> = st.tabs(["Home", "Data Input"<#if hasDatabase>, "Database"</#if>])

    with tab1:
        st.subheader("Home")
        st.write("This is your Streamlit dashboard for ${projectName}")

        # Example metrics
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Metric 1", "100", "10%")
        with col2:
            st.metric("Metric 2", "200", "-5%")
        with col3:
            st.metric("Metric 3", "300", "15%")

    with tab2:
        st.subheader("Data Input")

        # Form for data input
        with st.form("input_form"):
            name = st.text_input("Name", placeholder="Enter your name")
            message = st.text_area("Message", placeholder="Enter a message")

            submitted = st.form_submit_button("Submit")
            if submitted:
                if name and message:
                    st.success(f"Received: {name} - {message}")
                    logger.info(f"Form submitted: {name}")
                else:
                    st.error("Please fill in all fields")

<#if hasDatabase>
    with tab3:
        st.subheader("Database Connection")

        if st.button("Test Database Connection"):
            try:
<#if has_mongodb??>
                # Test MongoDB connection
                collection = get_collection('test')
                collection.insert_one({'test': 'connection'})
                collection.delete_one({'test': 'connection'})
                st.success("✅ MongoDB connection successful!")
<#elseif has_redis??>
                # Test Redis connection
                redis_client = get_redis_client()
                redis_client.ping()
                st.success("✅ Redis connection successful!")
<#else>
                # Test SQL database connection
                session = get_db_session()
                session.close()
                st.success("✅ Database connection successful!")
</#if>
            except Exception as e:
                st.error(f"❌ Database connection failed: {e}")
                logger.error(f"Database test failed: {e}")

</#if>
    # Footer
    st.markdown("---")
    st.caption("Built with Streamlit • Generated by Genesis")


if __name__ == "__main__":
    # Configure logging
    logging.basicConfig(level=logging.INFO)

    # Run Streamlit app
    main()
