#!/bin/bash
# Development Server Script for ${projectName}
# Generated by Genesis

set -e

# Check if virtual environment exists
if [ ! -d "venv" ]; then
    echo "❌ Virtual environment not found. Please run ./setup_venv.sh first."
    exit 1
fi

# Activate virtual environment
source venv/bin/activate

echo "🚀 Starting ${projectName} development server..."
echo ""

<#if has_flask??>
# Run Flask development server
export FLASK_APP=app.py
export FLASK_ENV=development
python main.py
<#elseif has_fastapi??>
# Run FastAPI development server with auto-reload
uvicorn main:app --reload --host 0.0.0.0 --port 8000
<#elseif has_django??>
# Run Django development server
python manage.py migrate --noinput
python manage.py runserver 0.0.0.0:8000
<#elseif has_streamlit??>
# Run Streamlit app
streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
<#elseif has_tkinter?? || has_pyqt5??>
# Run GUI application
python gui_app.py
<#else>
# Run application
python main.py
</#if>
