@echo off
REM Development Server Script for ${projectName}
REM Generated by Genesis

REM Check if virtual environment exists
if not exist "venv" (
    echo ❌ Virtual environment not found. Please run setup_venv.bat first.
    exit /b 1
)

REM Activate virtual environment
call venv\Scripts\activate.bat

echo 🚀 Starting ${projectName} development server...
echo.

<#if has_flask??>
REM Run Flask development server
set FLASK_APP=app.py
set FLASK_ENV=development
python main.py
<#elseif has_fastapi??>
REM Run FastAPI development server with auto-reload
uvicorn main:app --reload --host 0.0.0.0 --port 8000
<#elseif has_django??>
REM Run Django development server
python manage.py migrate --noinput
python manage.py runserver 0.0.0.0:8000
<#elseif has_streamlit??>
REM Run Streamlit app
streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
<#elseif has_tkinter?? || has_pyqt5??>
REM Run GUI application
python gui_app.py
<#else>
REM Run application
python main.py
</#if>
