#!/bin/bash
# Virtual Environment Setup Script for ${projectName}
# Generated by Genesis

set -e

echo "🚀 Setting up ${projectName}..."
echo ""

# Check Python version
if ! command -v python${pythonVersion} &> /dev/null; then
    echo "❌ Python ${pythonVersion} not found. Please install Python ${pythonVersion} first."
    exit 1
fi

echo "✓ Python ${pythonVersion} found"

# Create virtual environment
echo "📦 Creating virtual environment..."
python${pythonVersion} -m venv venv

# Activate virtual environment
echo "✓ Virtual environment created"
echo "📥 Installing dependencies..."

# Activate and install
source venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt

echo ""
echo "✅ Setup complete!"
echo ""
echo "To activate the virtual environment:"
echo "  source venv/bin/activate"
echo ""
<#if has_flask??>
echo "To run the Flask application:"
echo "  python main.py"
echo "  or: ./run_dev.sh"
<#elseif has_fastapi??>
echo "To run the FastAPI application:"
echo "  python main.py"
echo "  or: ./run_dev.sh"
echo "  API docs: http://localhost:8000/docs"
<#elseif has_django??>
echo "To run the Django application:"
echo "  python manage.py migrate"
echo "  python manage.py runserver"
echo "  or: ./run_dev.sh"
<#elseif has_streamlit??>
echo "To run the Streamlit app:"
echo "  streamlit run streamlit_app.py"
echo "  or: ./run_dev.sh"
<#elseif has_tkinter?? || has_pyqt5??>
echo "To run the GUI application:"
echo "  python gui_app.py"
echo "  or: ./run_dev.sh"
<#else>
echo "To run the application:"
echo "  python main.py"
</#if>
echo ""
