@echo off
REM Virtual Environment Setup Script for ${projectName}
REM Generated by Genesis

echo 🚀 Setting up ${projectName}...
echo.

REM Check Python version
python --version >nul 2>&1
if errorlevel 1 (
    echo ❌ Python not found. Please install Python ${pythonVersion} first.
    exit /b 1
)

echo ✓ Python found

REM Create virtual environment
echo 📦 Creating virtual environment...
python -m venv venv

REM Activate virtual environment
echo ✓ Virtual environment created
echo 📥 Installing dependencies...

call venv\Scripts\activate.bat
python -m pip install --upgrade pip
pip install -r requirements.txt

echo.
echo ✅ Setup complete!
echo.
echo To activate the virtual environment:
echo   venv\Scripts\activate
echo.
<#if has_flask??>
echo To run the Flask application:
echo   python main.py
echo   or: run_dev.bat
<#elseif has_fastapi??>
echo To run the FastAPI application:
echo   python main.py
echo   or: run_dev.bat
echo   API docs: http://localhost:8000/docs
<#elseif has_django??>
echo To run the Django application:
echo   python manage.py migrate
echo   python manage.py runserver
echo   or: run_dev.bat
<#elseif has_streamlit??>
echo To run the Streamlit app:
echo   streamlit run streamlit_app.py
echo   or: run_dev.bat
<#elseif has_tkinter?? || has_pyqt5??>
echo To run the GUI application:
echo   python gui_app.py
echo   or: run_dev.bat
<#else>
echo To run the application:
echo   python main.py
</#if>
echo.
pause
