# MongoDB Database Usage Instructions

This document explains how to use MongoDB with ${projectName}.

## Configuration

Database settings are configured in `.env` file:

```env
MONGO_URI=mongodb://localhost:27017/${projectName}
```

## Prerequisites

1. **Install MongoDB:**
   - Ubuntu/Debian: `sudo apt-get install mongodb`
   - macOS: `brew tap mongodb/brew && brew install mongodb-community`
   - Windows: Download from https://www.mongodb.com/try/download/community

2. **Start MongoDB service:**
   ```bash
   # Linux
   sudo service mongod start

   # macOS
   brew services start mongodb-community

   # Windows
   # MongoDB service starts automatically
   ```

## Usage

### Basic Connection

```python
from config.db_connection import get_database, get_collection

# Get database
db = get_database()

# Get collection
users = get_collection('users')
```

### CRUD Operations

```python
from config.db_connection import get_collection

# Get users collection
users = get_collection('users')

# Create (Insert)
user_id = users.insert_one({
    'username': 'john_doe',
    'email': 'john@example.com',
    'age': 30
}).inserted_id
print(f"Created user with ID: {user_id}")

# Read (Find)
user = users.find_one({'username': 'john_doe'})
print(f"Found user: {user}")

# Find multiple documents
for user in users.find({'age': {'$gte': 25}}):
    print(f"User: {user['username']} - Age: {user['age']}")

# Update
result = users.update_one(
    {'username': 'john_doe'},
    {'$set': {'email': 'newemail@example.com'}}
)
print(f"Modified {result.modified_count} document(s)")

# Delete
result = users.delete_one({'username': 'john_doe'})
print(f"Deleted {result.deleted_count} document(s)")
```

### Advanced Queries

```python
from config.db_connection import get_collection

users = get_collection('users')

# Find with projection (select specific fields)
user = users.find_one(
    {'username': 'john_doe'},
    {'username': 1, 'email': 1, '_id': 0}
)

# Find with sorting
users_sorted = users.find().sort('age', -1)  # Descending

# Find with limit
users_limited = users.find().limit(10)

# Count documents
count = users.count_documents({'age': {'$gte': 25}})

# Aggregation
pipeline = [
    {'$match': {'age': {'$gte': 25}}},
    {'$group': {'_id': '$age', 'count': {'$sum': 1}}},
    {'$sort': {'count': -1}}
]
results = users.aggregate(pipeline)
```

### Indexes

```python
from config.db_connection import get_collection

users = get_collection('users')

# Create index
users.create_index('username', unique=True)
users.create_index([('email', 1), ('age', -1)])

# List indexes
for index in users.list_indexes():
    print(index)
```

## Data Modeling

### Example Document Schema

```python
user_document = {
    'username': 'john_doe',
    'email': 'john@example.com',
    'profile': {
        'first_name': 'John',
        'last_name': 'Doe',
        'age': 30
    },
    'tags': ['python', 'mongodb', 'developer'],
    'created_at': datetime.utcnow()
}
```

### Using Pydantic for Validation

```python
from pydantic import BaseModel
from datetime import datetime
from typing import List, Optional

class UserProfile(BaseModel):
    first_name: str
    last_name: str
    age: int

class User(BaseModel):
    username: str
    email: str
    profile: Optional[UserProfile] = None
    tags: List[str] = []
    created_at: datetime = datetime.utcnow()

# Use with MongoDB
user = User(
    username='john_doe',
    email='john@example.com',
    profile=UserProfile(first_name='John', last_name='Doe', age=30)
)

users.insert_one(user.dict())
```

## Troubleshooting

### Connection refused
- Ensure MongoDB is running: `sudo service mongod status`
- Check MongoDB logs: `sudo tail -f /var/log/mongodb/mongod.log`

### Authentication failed
- Check connection string in `.env`
- If authentication is enabled, use: `mongodb://username:password@localhost:27017/${projectName}`

### Database or collection doesn't exist
- MongoDB creates databases and collections automatically when you first write to them
- No need to explicitly create them

## Best Practices

1. **Use connection pooling** (pymongo handles this automatically)
2. **Create indexes** for frequently queried fields
3. **Use aggregation pipeline** for complex queries
4. **Validate data** with Pydantic or similar
5. **Handle connection errors** gracefully

## Resources

- MongoDB Documentation: https://docs.mongodb.com/
- PyMongo Documentation: https://pymongo.readthedocs.io/
- MongoDB University: https://university.mongodb.com/

---

Generated by Genesis - ${currentDate}
