package com.stephen_oosthuizen.genesis.service;

import com.stephen_oosthuizen.genesis.dto.ProjectRequest;
import com.stephen_oosthuizen.genesis.exception.ComponentNotFoundException;
import com.stephen_oosthuizen.genesis.exception.GenerationException;
import com.stephen_oosthuizen.genesis.metadata.ComponentRegistry;
import com.stephen_oosthuizen.genesis.model.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Main service for orchestrating Python project generation.
 * Coordinates template rendering, file generation, and ZIP creation.
 */
@Service
@Slf4j
@RequiredArgsConstructor
public class ProjectGenerationService {
    private final ComponentRegistry componentRegistry;
    private final TemplateService templateService;
    private final ZipService zipService;
    private final DependencyResolver dependencyResolver;

    /**
     * Generate a complete Python project based on the request
     *
     * @param request User's project generation request
     * @return ZIP file as byte array
     */
    public byte[] generateProject(ProjectRequest request) {
        log.info("Starting project generation: {}", request.getProjectName());

        try {
            // 1. Build project configuration
            ProjectConfiguration config = buildConfiguration(request);

            // 2. Generate all project files
            List<ProjectFile> files = generateAllFiles(config);

            // 3. Create ZIP archive
            byte[] zipBytes = zipService.createZip(files, request.getProjectName());

            log.info("Project generation completed successfully: {} ({} bytes)",
                    request.getProjectName(), zipBytes.length);
            return zipBytes;

        } catch (Exception e) {
            log.error("Project generation failed for: {}", request.getProjectName(), e);
            throw new GenerationException("Failed to generate project: " + e.getMessage(), e);
        }
    }

    /**
     * Build ProjectConfiguration from request
     */
    private ProjectConfiguration buildConfiguration(ProjectRequest request) {
        log.debug("Building project configuration");

        // Resolve components
        Set<Component> components = resolveComponents(request.getComponents());

        // Validate compatibility
        dependencyResolver.validateCompatibility(components);

        // Log any warnings
        List<String> warnings = dependencyResolver.getWarnings(components);
        if (!warnings.isEmpty()) {
            log.info("Validation warnings: {}", warnings);
        }

        // Build configuration
        ProjectConfiguration config = ProjectConfiguration.builder()
                .projectName(request.getProjectName())
                .description(request.getDescription() != null ? request.getDescription() : "A Python project generated by Genesis")
                .pythonVersion(request.getPythonVersion())
                .authorName(request.getAuthorName())
                .authorEmail(request.getAuthorEmail())
                .components(components)
                .build();

        log.debug("Configuration built with {} components", components.size());
        return config;
    }

    /**
     * Resolve component IDs to Component objects
     */
    private Set<Component> resolveComponents(List<String> componentIds) {
        Set<Component> components = new HashSet<>();

        for (String componentId : componentIds) {
            Component component = componentRegistry.getComponent(componentId)
                    .orElseThrow(() -> new ComponentNotFoundException(
                            "Component not found: " + componentId));
            components.add(component);
        }

        return components;
    }

    /**
     * Generate all project files
     */
    private List<ProjectFile> generateAllFiles(ProjectConfiguration config) {
        log.debug("Generating project files");
        List<ProjectFile> files = new ArrayList<>();

        TemplateContext context = new TemplateContext(config);

        // Generate base files
        files.addAll(generateBaseFiles(context));

        // Generate component-specific files
        files.addAll(generateComponentFiles(context, config));

        // Generate documentation files
        files.addAll(generateDocumentationFiles(context, config));

        log.info("Generated {} files", files.size());
        return files;
    }

    /**
     * Generate base project files (always included)
     */
    private List<ProjectFile> generateBaseFiles(TemplateContext context) {
        log.debug("Generating base files");
        List<ProjectFile> files = new ArrayList<>();

        // requirements.txt
        files.add(ProjectFile.of(
                "requirements.txt",
                templateService.renderTemplate("base/requirements.txt.ftl", context)
        ));

        // README.md
        files.add(ProjectFile.of(
                "README.md",
                templateService.renderTemplate("base/README.md.ftl", context)
        ));

        // .gitignore
        files.add(ProjectFile.of(
                ".gitignore",
                templateService.renderTemplate("base/.gitignore.ftl", context)
        ));

        // main.py
        files.add(ProjectFile.of(
                "main.py",
                templateService.renderTemplate("base/main.py.ftl", context)
        ));

        // config.py
        files.add(ProjectFile.of(
                "config/config.py",
                templateService.renderTemplate("base/config.py.ftl", context)
        ));

        // .env.template
        files.add(ProjectFile.of(
                ".env.template",
                templateService.renderTemplate("base/.env.template.ftl", context)
        ));

        // Setup scripts (executable)
        files.add(ProjectFile.executable(
                "setup_venv.sh",
                templateService.renderTemplate("scripts/setup_venv.sh.ftl", context)
        ));

        files.add(ProjectFile.of(
                "setup_venv.bat",
                templateService.renderTemplate("scripts/setup_venv.bat.ftl", context)
        ));

        // Development run scripts (executable)
        files.add(ProjectFile.executable(
                "run_dev.sh",
                templateService.renderTemplate("scripts/run_dev.sh.ftl", context)
        ));

        files.add(ProjectFile.of(
                "run_dev.bat",
                templateService.renderTemplate("scripts/run_dev.bat.ftl", context)
        ));

        log.debug("Generated {} base files", files.size());
        return files;
    }

    /**
     * Generate component-specific files
     */
    private List<ProjectFile> generateComponentFiles(TemplateContext context, ProjectConfiguration config) {
        log.debug("Generating component files");
        List<ProjectFile> files = new ArrayList<>();

        for (Component component : config.getComponents()) {
            log.debug("Processing component: {}", component.getId());

            for (String templatePath : component.getTemplatePaths()) {
                try {
                    String content = templateService.renderTemplate(templatePath, context);

                    // Determine output path from template path
                    String outputPath = determineOutputPath(templatePath, component, config.getProjectName());

                    files.add(ProjectFile.of(outputPath, content));
                    log.debug("Generated file from template: {} -> {}", templatePath, outputPath);

                } catch (Exception e) {
                    log.error("Failed to render template: {}", templatePath, e);
                    throw new GenerationException("Failed to render template: " + templatePath, e);
                }
            }
        }

        return files;
    }

    /**
     * Generate documentation files
     */
    private List<ProjectFile> generateDocumentationFiles(TemplateContext context, ProjectConfiguration config) {
        log.debug("Generating documentation files");
        List<ProjectFile> files = new ArrayList<>();

        for (Component component : config.getComponents()) {
            for (String docPath : component.getDocumentationPaths()) {
                try {
                    String content = templateService.renderTemplate(docPath, context);
                    String outputPath = determineOutputPath(docPath, component, config.getProjectName());
                    files.add(ProjectFile.of(outputPath, content));
                } catch (Exception e) {
                    log.warn("Failed to render documentation: {}", docPath, e);
                    // Don't fail the entire generation for missing docs
                }
            }
        }

        return files;
    }

    /**
     * Determine output file path from template path
     * Removes category directories and .ftl extension
     */
    private String determineOutputPath(String templatePath, Component component, String projectName) {
        // Remove .ftl extension
        String path = templatePath.replace(".ftl", "");

        // Handle web framework templates
        if (path.startsWith("web/")) {
            String[] parts = path.split("/");
            String fileName = parts[parts.length - 1];
            String frameworkName = parts[1];

            // Django has special structure
            if ("django".equals(frameworkName)) {
                if ("manage.py".equals(fileName)) {
                    return "manage.py";
                } else {
                    // settings.py, urls.py go into projectName/ directory
                    return projectName + "/" + fileName;
                }
            }

            // Flask, FastAPI: files go to root
            return fileName;
        }

        // Handle database templates
        if (path.startsWith("database/")) {
            // database/postgresql/db_connection.py -> config/db_connection_postgresql.py
            String[] parts = path.split("/");
            String databaseType = parts[1]; // e.g., "postgresql", "mongodb"
            String fileName = parts[parts.length - 1];

            // Rename db_connection.py to include database type
            if (fileName.equals("db_connection.py")) {
                return "config/db_connection_" + databaseType + ".py";
            }

            // Documentation files keep original name
            return "config/" + fileName;
        }

        // Handle security templates
        if (path.startsWith("security/")) {
            // security/jwt/jwt_handler.py -> config/jwt_handler.py
            String[] parts = path.split("/");
            return "config/" + parts[parts.length - 1];
        }

        // Handle GUI templates
        if (path.startsWith("gui/")) {
            // gui/tkinter/gui_app.py -> gui_app.py (root level)
            String[] parts = path.split("/");
            return parts[parts.length - 1];
        }

        // Handle testing templates
        if (path.startsWith("testing/")) {
            // testing/unittest/test_example.py -> tests/test_example.py
            String[] parts = path.split("/");
            return "tests/" + parts[parts.length - 1];
        }

        // Handle docker templates
        if (path.startsWith("docker/")) {
            // docker/Dockerfile -> Dockerfile (root level)
            String[] parts = path.split("/");
            return parts[parts.length - 1];
        }

        // Default: just remove .ftl
        return path;
    }
}
