# OAuth2 Authentication Guide

OAuth2 allows users to login with Google, GitHub, and other providers.

## Configuration

Add to `.env`:

```env
# Google OAuth2
GOOGLE_CLIENT_ID=your_google_client_id
GOOGLE_CLIENT_SECRET=your_google_client_secret

# GitHub OAuth2
GITHUB_CLIENT_ID=your_github_client_id
GITHUB_CLIENT_SECRET=your_github_client_secret

# Callback URL
OAUTH_CALLBACK_URL=http://localhost:<#if has_flask??>5000<#else>8000</#if>/callback
```

## Setup OAuth2 Apps

### Google
1. Go to: https://console.cloud.google.com/
2. Create project → Enable Google+ API
3. Create OAuth2 credentials
4. Add callback URL: `http://localhost:5000/callback`

### GitHub
1. Go to: https://github.com/settings/developers
2. New OAuth App
3. Add callback URL: `http://localhost:5000/callback`

## Resources

- Authlib Documentation: https://docs.authlib.org/
- OAuth2 Specification: https://oauth.net/2/

---

Generated by Genesis - ${currentDate}
