# ${projectName} - Git Ignore
# Generated by Genesis

# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# Virtual Environment
venv/
env/
ENV/
.venv

# Environment Variables
.env
.env.local

# IDEs
.vscode/
.idea/
*.swp
*.swo
*~
.DS_Store

# Testing
.pytest_cache/
.coverage
htmlcov/
.tox/
.hypothesis/

<#if hasDatabase>
# Database
*.db
*.sqlite
*.sqlite3
</#if>

# Logs
*.log
logs/

# OS
Thumbs.db
.DS_Store

<#if hasDocker>
# Docker
docker-compose.override.yml
</#if>
