#!/usr/bin/env python3
"""
${projectName} - Main Entry Point
Generated by Genesis on ${currentDate}

<#if description??>
${description}
</#if>
"""

import sys
import logging
from config.config import Config

<#if has_tkinter?? || has_pyqt5??>
# GUI application
from gui_app import main as gui_main
<#elseif has_streamlit??>
# Streamlit application
# Run with: streamlit run streamlit_app.py
import streamlit_app
<#else>
<#if has_flask??>
from app import create_app
<#elseif has_fastapi??>
import uvicorn
from app import app
<#elseif has_django??>
import os
import django
</#if>
</#if>

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def main():
    """Main application entry point"""
<#if has_tkinter?? || has_pyqt5??>
    # Launch GUI application
    gui_main()
<#elseif has_streamlit??>
    # Streamlit application
    # Run with: streamlit run streamlit_app.py
    print("To run this Streamlit app, use:")
    print("  streamlit run streamlit_app.py")
<#else>
    logger.info("Starting ${projectName}...")

    # Load configuration
    config = Config()
    logger.info(f"Environment: {config.environment}")

<#if hasDatabase>
    # Database connections available in config/
    # Import the database modules you need:
<#if has_postgresql??>
    # from config.db_connection_postgresql import get_db_session as get_postgres_session
</#if>
<#if has_mysql??>
    # from config.db_connection_mysql import get_db_session as get_mysql_session
</#if>
<#if has_mongodb??>
    # from config.db_connection_mongodb import get_database as get_mongo_db
</#if>
<#if has_sqlite??>
    # from config.db_connection_sqlite import get_db_session as get_sqlite_session
</#if>
<#if has_redis??>
    # from config.db_connection_redis import get_redis_client
</#if>
    logger.info("Database modules available in config/")

</#if>
<#if has_flask??>
    # Create and run Flask application
    app = create_app()
    app.run(
        host=config.host,
        port=config.port,
        debug=config.debug
    )
<#elseif has_fastapi??>
    # Run FastAPI application
    uvicorn.run(
        "main:app",
        host=config.host,
        port=config.port,
        reload=config.debug
    )
<#elseif has_django??>
    # Django setup
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', '${projectName}.settings')
    django.setup()

    # Run Django development server
    from django.core.management import execute_from_command_line
    execute_from_command_line(['manage.py', 'runserver', f'{config.host}:{config.port}'])
<#else>
    # Your application logic here
    logger.info("${projectName} is running")
    print("Hello from ${projectName}!")
</#if>
</#if>


if __name__ == "__main__":
    main()
