# ${projectName}

${description}

**Generated by Genesis** - Python Project Initializr
**Date:** ${currentDate}
**Python Version:** ${pythonVersion}

---

## 🚀 Quickstart

Get up and running in 3 simple steps:

### Linux/macOS:
```bash
# 1. Setup (creates venv + installs dependencies)
chmod +x setup_venv.sh run_dev.sh
./setup_venv.sh

# 2. Configure (copy and edit .env)
cp .env.template .env
# Edit .env with your settings

# 3. Run!
./run_dev.sh
```

### Windows:
```cmd
# 1. Setup (creates venv + installs dependencies)
setup_venv.bat

# 2. Configure (copy and edit .env)
copy .env.template .env
# Edit .env with your settings

# 3. Run!
run_dev.bat
```

---

## 📦 Project Overview

This project was generated with the following components:

<#list components as component>
- **${component.name}** (${component.typeDisplayName}): ${component.description}
</#list>

---

## 📖 Detailed Setup Instructions

### 1. Create Virtual Environment

```bash
python${pythonVersion} -m venv venv
source venv/bin/activate  # On Windows: venv\Scripts\activate
```

### 2. Install Dependencies

```bash
pip install -r requirements.txt
```

### 3. Configure Environment Variables

Copy `.env.template` to `.env` and update with your configuration:

```bash
cp .env.template .env
```

<#if hasDatabase>
### 4. Database Setup

<#assign dbCount = 0>
<#if has_postgresql??><#assign dbCount = dbCount + 1></#if>
<#if has_mysql??><#assign dbCount = dbCount + 1></#if>
<#if has_mongodb??><#assign dbCount = dbCount + 1></#if>
<#if has_sqlite??><#assign dbCount = dbCount + 1></#if>
<#if has_redis??><#assign dbCount = dbCount + 1></#if>

<#if (dbCount > 1)>
This project includes multiple database connections. Each database has its own connection module in `config/`:
<#else>
Configure your database connection in the `.env` file.
</#if>

<#if has_postgresql??>
**PostgreSQL:** See `config/db_connection_postgresql.py`
- Update `DATABASE_URL` in `.env`
- Ensure PostgreSQL is running
- Create your database: `createdb ${projectName}`

</#if>
<#if has_mysql??>
**MySQL:** See `config/db_connection_mysql.py`
- Update `DATABASE_URL` in `.env`
- Ensure MySQL is running
- Create your database: `CREATE DATABASE ${projectName};`

</#if>
<#if has_mongodb??>
**MongoDB:** See `config/db_connection_mongodb.py`
- Update `MONGO_URI` in `.env`
- Ensure MongoDB is running

</#if>
<#if has_sqlite??>
**SQLite:** See `config/db_connection_sqlite.py`
- No setup needed - database file created automatically at `data/${projectName}.db`

</#if>
<#if has_redis??>
**Redis:** See `config/db_connection_redis.py`
- Update `REDIS_URI` in `.env`
- Ensure Redis is running

</#if>
</#if>

## Running the Application

<#if has_tkinter?? || has_pyqt5??>
### Launch GUI Application

```bash
python gui_app.py
```

<#elseif has_streamlit??>
### Launch Streamlit Dashboard

```bash
streamlit run streamlit_app.py
```

The dashboard will open in your browser at `http://localhost:8501`

<#elseif hasWebFramework>
### Start the Web Server

```bash
python main.py
```

<#if has_flask??>
The Flask application will start on `http://localhost:5000`
<#elseif has_fastapi??>
The FastAPI application will start on `http://localhost:8000`

**Interactive API Documentation:**
- Swagger UI: `http://localhost:8000/docs`
- ReDoc: `http://localhost:8000/redoc`
<#elseif has_django??>
Run migrations first:
```bash
python manage.py migrate
```

Then start the server:
```bash
python manage.py runserver
```

Access admin panel at `http://localhost:8000/admin`
</#if>
<#else>
```bash
python main.py
```
</#if>

<#if hasDocker>
### Running with Docker

```bash
# Build and run with Docker Compose
docker-compose up --build

# Run in detached mode
docker-compose up -d

# Stop containers
docker-compose down
```
</#if>

## Testing

<#if hasTesting>
Run tests with pytest:

```bash
pytest
```

Generate coverage report:

```bash
pytest --cov=${projectName} --cov-report=html
```
<#else>
Add your tests in a `tests/` directory and install pytest:

```bash
pip install pytest
pytest
```
</#if>

## Project Structure

```
${projectName}/
├── main.py                 # Application entry point
├── config/                 # Configuration modules
│   ├── config.py          # Main configuration
<#if hasDatabase>
│   └── db_connection.py   # Database connection
</#if>
├── requirements.txt        # Python dependencies
├── .env.template          # Environment variables template
├── .gitignore             # Git ignore rules
└── README.md              # This file
```

## Additional Documentation

<#if hasDatabase>
- See database usage instructions in the documentation
</#if>
<#if hasSecurity>
- See security setup instructions in the documentation
</#if>

## Development

### Code Style

Follow PEP 8 style guidelines:

```bash
pip install flake8 black
black .
flake8 .
```

### Git Workflow

```bash
git init
git add .
git commit -m "Initial commit"
```

## License

<#if authorName??>
Copyright (c) ${currentYear} ${authorName}
<#else>
Copyright (c) ${currentYear}
</#if>

---

**Generated by Genesis** - https://github.com/ByteSizedLaw/Genesis
