# ${projectName} - Python Dependencies
# Generated by Genesis on ${currentDate}

<#if hasWebFramework>
# Web Framework
<#list components as component>
<#if component.typeName == "WEB_FRAMEWORK">
<#list component.dependencies as dep>
${dep}
</#list>
</#if>
</#list>

</#if>
<#if hasDatabase>
# Database
<#list components as component>
<#if component.typeName == "DATABASE">
<#list component.dependencies as dep>
${dep}
</#list>
</#if>
</#list>

</#if>
<#if hasSecurity>
# Security
<#list components as component>
<#if component.typeName == "SECURITY">
<#list component.dependencies as dep>
${dep}
</#list>
</#if>
</#list>

</#if>
<#if hasTesting>
# Testing
<#list components as component>
<#if component.typeName == "TESTING">
<#list component.dependencies as dep>
${dep}
</#list>
</#if>
</#list>

</#if>
# Configuration and utilities
python-dotenv==1.0.0
